// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/easyops-cn/go-proto-giraffe/giraffe.proto

package giraffeproto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Contract struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_45c7a1bac31e4345, []int{0}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contract) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Contract)(nil), "giraffeproto.Contract")
}

func init() {
	proto.RegisterFile("github.com/easyops-cn/go-proto-giraffe/giraffe.proto", fileDescriptor_45c7a1bac31e4345)
}

var fileDescriptor_45c7a1bac31e4345 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x4d, 0x2c, 0xae, 0xcc, 0x2f, 0x28, 0xd6, 0x4d,
	0xce, 0xd3, 0x4f, 0xcf, 0xd7, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4d, 0xcf, 0x2c, 0x4a, 0x4c,
	0x4b, 0x4b, 0xd5, 0x87, 0xd2, 0x7a, 0x60, 0x51, 0x21, 0x1e, 0x28, 0x17, 0xcc, 0x53, 0xb2, 0xe0,
	0xe2, 0x70, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52,
	0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x98, 0xc0, 0xc2, 0x30, 0xae, 0x93, 0x69, 0x94, 0x31, 0x71,
	0xf6, 0x5b, 0x23, 0x5b, 0x98, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68,
	0x0d, 0x68, 0xe1, 0xbd, 0x00, 0x00, 0x00,
}
